// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

Future<ScanResult> scanRootDir({
  required String rootPath,
  required Map<String, PlatformInt64> knownFiles,
}) => RustLib.instance.api.crateApiScannerScanRootDir(
  rootPath: rootPath,
  knownFiles: knownFiles,
);

class AudioFileMetadata {
  final String path;
  final String? title;
  final String? artist;
  final String? album;
  final BigInt? durationSecs;
  final String format;
  final PlatformInt64 lastModified;

  const AudioFileMetadata({
    required this.path,
    this.title,
    this.artist,
    this.album,
    this.durationSecs,
    required this.format,
    required this.lastModified,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      durationSecs.hashCode ^
      format.hashCode ^
      lastModified.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioFileMetadata &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          durationSecs == other.durationSecs &&
          format == other.format &&
          lastModified == other.lastModified;
}

class ScanResult {
  final List<AudioFileMetadata> newOrModified;
  final List<String> deletedPaths;

  const ScanResult({required this.newOrModified, required this.deletedPaths});

  @override
  int get hashCode => newOrModified.hashCode ^ deletedPaths.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanResult &&
          runtimeType == other.runtimeType &&
          newOrModified == other.newOrModified &&
          deletedPaths == other.deletedPaths;
}
